apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: topomojo
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: topomojo
    server: https://kubernetes.default.svc
  project: default
  syncPolicy:
    automated:
      prune: true
    syncOptions:
    - CreateNamespace=true
  sources:
  - path: argocd/apps/topomojo/kustomize/overlays/appliance
    repoURL: file:///crucible-repo/crucible-appliance-argo
    targetRevision: main

