apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default

configMapGenerator:
- name: root-ca
  files:
  - root-ca.crt=files/root-ca.pem

generatorOptions:
  disableNameSuffixHash: true

helmCharts:
- name: moodle
  includeCRDs: true
  version: 23.0.7
  repo: https://charts.bitnami.com/bitnami
  releaseName: appliance
  valuesFile: files/moodle.values.yaml