apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: longhorn-system
helmCharts:
- name: longhorn
  includeCRDs: true
  version: 1.5.3
  repo: https://charts.longhorn.io
  releaseName: appliance
  valuesFile: files/longhorn.values.yaml
resources: 
- namespace.yaml











