apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: longhorn-system
helmCharts:
- name: longhorn
  includeCRDs: true
  version: 1.6.0
  repo: https://charts.longhorn.io
  releaseName: appliance
  valuesFile: files/longhorn.values.1.6.0.yaml
resources: 
- namespace.yaml











