apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: gitea
helmCharts:
- name: longhorn
  includeCRDs: true
  version: 0.27.0
  repo: https://helm.releases.hashicorp.com
  releaseName: appliance
  valuesFile: files/longhorn.values.yaml
resources: 
- namespace.yaml











