# hin blueprint sei/blueprint -f blueprint.values.yaml
blueprint-api:
  image:
    tag: "0.3.11"

# Ingress configuration example for NGINX
# TLS and Host URLs need configured
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: <path:gauntletdevk8s/data/shared#ingress-class>
      nginx.ingress.kubernetes.io/proxy-read-timeout: '86400'
      nginx.ingress.kubernetes.io/proxy-send-timeout: '86400'
      nginx.ingress.kubernetes.io/use-regex: "true"
    hosts:
      - host: <path:gauntletdevk8s/data/shared#domain>
        paths:
          - path: /blueprint/(api|swagger|hubs)
            pathType: Prefix
    tls:
      - secretName: appliance-cert
        hosts:
         - <path:gauntletdevk8s/data/shared#domain>

  resources:
    requests:
      cpu: 200m
      memory: 512Mi

  env:
    PathBase: "/blueprint"
    # CORS policy settings.
    # The first entry should be the URL to Blueprint
    CorsPolicy__Origins__0: https://<path:gauntletdevk8s/data/shared#domain>
    
    CorsPolicy__AllowAnyMethod: true
    CorsPolicy__AllowAnyHeader: true

    # Connection String to database
    # database requires the 'uuid-ossp' extension installed
    ConnectionStrings__PostgreSQL: <path:fortress-prod/data/blueprint#blueprint-db-connection-string>
    
    # OAuth2 Identity Client for Application
    Authorization__Authority: https://fortress.sei.cmu.edu/keycloak/realms/crucible
    Authorization__AuthorizationUrl: https://fortress.sei.cmu.edu/keycloak/realms/crucible/protocol/openid-connect/auth
    Authorization__TokenUrl: https://fortress.sei.cmu.edu/keycloak/realms/crucible/protocol/openid-connect/token
    Authorization__AuthorizationScope: "blueprint-api"
    Authorization__ClientId: "<path:gauntletdevk8s/data/shared#oauth-env>_<path:gauntletdevk8s/data/shared#oauth-gid>_blueprint-api"
    Authorization__ClientName: "Blueprint API"


    Logging__Debug__LogLevel__System: "Warning"
    Logging__Debug__LogLevel__Default: "Warning"
    Logging__Debug__LogLevel__Microsoft: "Warning"
    Logging__Debug__FormatterName: "json"
    Logging__Debug__FormatterOptions__SingleLine: true
    Logging__Debug__FormatterOptions__TimestampFormat: "HH:mm:ss"
    Logging__Debug__FormatterOptions__UseUtcTimestamp: true
    Logging__Console__LogLevel__System: "Warning"
    Logging__Console__LogLevel__Default: "Warning"
    Logging__Console__LogLevel__Microsoft: "Warning"
    Logging__Console__FormatterName: "json"
    Logging__Console__FormatterOptions__SingleLine: true
    Logging__Console__FormatterOptions__TimestampFormat: "HH:mm:ss"
    Logging__Console__FormatterOptions__UseUtcTimestamp: true


blueprint-ui:
  # Docker image release version
  image:
    tag: "0.3.13"

  # Ingress configuration example for NGINX
  # TLS and Host URLs need configured
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: <path:gauntletdevk8s/data/shared#ingress-class>
      nginx.ingress.kubernetes.io/use-regex: "true"
    hosts:
      - host: <path:gauntletdevk8s/data/shared#domain>
        paths:
          - path: /blueprint(/|$)(.*)
            pathType: Prefix
    tls:
      - secretName: appliance-cert
        hosts:
         - <path:gauntletdevk8s/data/shared#domain>

  resources:
    requests:
      cpu: 200m
      memory: 10Mi

  env:
    APP_BASEHREF: "/blueprint"
  # Config app settings with a JSON file.
  # These values correspond to an OpenID connect client and
  # some basic configuration
  settings: |-
    {
      "ApiUrl": "https://fortress.sei.cmu.edu/blueprint",
      "OIDCSettings": {
        "authority": "https://fortress.sei.cmu.edu/keycloak/realms/crucible",
        "client_id": "<path:gauntletdevk8s/data/shared#oauth-env>_<path:gauntletdevk8s/data/shared#oauth-gid>_blueprint-api",
        "redirect_uri": "https://fortress.sei.cmu.edu/blueprint/auth-callback",
        "post_logout_redirect_uri": "https://fortress.sei.cmu.edu/blueprint",
        "response_type": "code",
        "scope": "openid profile blueprint-api",
        "automaticSilentRenew": true,
        "silent_redirect_uri": "https://fortress.sei.cmu.edu/blueprint/auth-callback-silent"
      },
      "AppTitle": "Blueprint",
      "AppTopBarHexColor": "#2d69b4",
      "AppTopBarHexTextColor": "#FFFFFF",
      "AppTopBarText": "Blueprint  -  Collaborative MSEL Creation",
      "AppTopBarImage": "/blueprint/assets/img/pencil-ruler-white.png",
      "UseLocalAuthStorage": false
    }
