apiVersion: v1
kind: Secret
metadata:
  name: fortress-tls
type: kubernetes.io/tls
stringData:
  tls.crt: |
    <path:fortress-prod/data/shared#fortress-tls-fullchain>
  tls.key: |
    <path:fortress-prod/data/shared#fortress-tls-key>