# - op: replace
#   path: /spec/jobTemplate/spec/template/spec/volumes/0
#   value:
#     name: appliance-mkdocs-material-entry
#     configMap:
#       name: appliance-mkdocs-material-entry
#       defaultMode: 0775 

- op: add
  path: /spec/jobTemplate/spec/template/spec/volumes/-
  value:
    name: crucible-ssl-vol
    secret:
      secretName: crucible-certs
      items:
      - key: crucible-ca.crt
        path: crucible-ca.crt
    
- op: add 
  path: /spec/jobTemplate/spec/template/spec/initContainers/0/volumeMounts/-
  value:
    name: crucible-ssl-vol
    mountPath: /usr/local/share/ca-certificates/crucible-ca.crt
    subPath: crucible-ca.crt
      
