apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: mkdocs
resources:
- ../../base

secretGenerator:
- name: crucible-certs
  files:
  - crucible-ca.crt=files/root-ca.pem

patches:
  - target:
      kind: Deployment
      name: appliance-mkdocs-material
    path: deployment.yaml

  - target:
      kind: CronJob
      name: appliance-cron
    path: cronjob.yaml
  
  # - target:
  #     kind: ConfigMap
  #     name: appliance-mkdocs-material-entry
  #   path: configmap-entry.yaml

generatorOptions:
  disableNameSuffixHash: true