#generate and deploy apps defined in the crucible folder
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  name: 2-monitoring
  namespace: argocd
spec:
  generators:
  - git:
      repoURL: https://github.com/sei-noconnor/crucible-appliance.git
      revision: offline-reorg
      files:
      - path: "argocd/apps/prod-argo/2-monitoring/*.json"
  template:
    metadata:
      name: '{{app.project_name}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/sei-noconnor/crucible-appliance.git
        targetRevision: '{{app.project_branch}}'
        path: "argocd/apps/prod-k8s/2-monitoring"
        plugin:
          name: argocd-vault-plugin
          env:
            - name: MANIFEST_TYPE
              value : '{{app.manifest_type}}'
            - name: ADDITIONAL_ARGS
              value: '{{app.helm_args}}'
            - name: CHART_VERSION
              value: '{{app.helm_chart_version}}'
            - name: HELM_REPO
              value: '{{app.helm_repo}}'
            - name: HELM_CHART
              value: '{{app.helm_chart}}'
            - name: HELM_RELEASE_NAME
              value: '{{app.project_name}}'
            - name: NAMESPACE
              value: '{{app.namespace}}'
            - name: VALUES_FILE
              value: '{{app.values_file}}'

      destination:
        server: https://kubernetes.default.svc
        namespace: monitoring
      syncPolicy:
        automated:
          prune: false
          selfHeal: false
