#generate and deploy apps defined in the crucible folder
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: appset-monitoring-fortress-prod
  namespace: argocd
spec:
  generators:
  - git:
      repoURL: https://fortress.sei.cmu.edu/gitea/fortress-manifests/fortress-prod-argo.git
      revision: HEAD
      files:
      - path: "apps/monitoring/*.json"
  template:
    metadata:
      name: '{{app.project_name}}'
    spec:
      project: default
      source:
        repoURL: https://fortress.sei.cmu.edu/gitea/fortress-manifests/fortress-prod-k8s.git
        targetRevision: '{{app.project_branch}}'
        path: "monitoring"
        plugin:
          name: avp-helm-multi
          env:
            - name: HELM_ARGS
              value: '{{app.helm_args}}'
            - name: CHART_VERSION
              value: '{{app.helm_chart_version}}'
            - name: HELM_REPO
              value: '{{app.helm_repo}}'
            - name: HELM_CHART
              value: '{{app.helm_chart_name}}'
            - name: HELM_RELEASE_NAME
              value: '{{app.project_name}}'
            - name: HTTP_PROXY
              value: 'http://proxy.sei.cmu.edu:8080'
      destination:
        server: https://cwd-gauntlet-prod-k8s-dns-io7cx2vb.hcp.usgovvirginia.cx.aks.containerservice.azure.us:443
        namespace: monitoring
      syncPolicy:
        automated:
          prune: false
          selfHeal: false
