apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: vault
helmCharts:
- name: vault
  includeCRDs: true
  version: 0.27.0
  repo: https://helm.releases.hashicorp.com
  releaseName: appliance
  valuesFile: files/vault.values.yaml
resources: 
- namespace.yaml











