apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cert-manager
secretGenerator:
  - name: root-ca
    files: 
    - tls.crt=$(cat files/intermediate-ca.crt files/root-ca.crt)
    - tls.key=files/root-ca.key
    type: "kubernetes.io/tls"
generatorOptions:
  disableNameSuffixHash: true
helmCharts:
- name: cert-manager
  includeCRDs: true
  version: v1.15.2
  repo: https://charts.jetstack.io
  releaseName: appliance
  valuesInline:
    installCRDs: true
    cainjector:
      enabled: true
resources: 
- namespace.yaml
- ClusterIssuer.yaml









