apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cert-manager
secretGenerator:
  - name: root-ca
    files: 
    - tls.crt=files/root-ca.pem
    - tls.key=files/root-ca.key
generatorOptions:
  disableNameSuffixHash: true
resources: 
- namespace.yaml
- ClusterIssuer.yaml










