apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default

helmGlobals:
  chartHome: ../../../../../../local-charts

helmCharts:
- name: misp
  includeCRDs: false
  version: 0.1.0
  releaseName: appliance
  namespace: default
  valuesFile: files/misp.values.yaml

resources: []