global:
  postgresql:
    auth:
      postgresPassword: "${ADMIN_PASS}"
image:
  registry: docker.io
  repository: bitnami/postgresql
  tag: 15.3.0-debian-11-r77
  pullPolicy: IfNotPresent
architecture: standalone
shmVolume:
  enabled: true
  sizeLimit: ""
  initdb:
    scripts: 
      keycloak_init.sql: |
        CREATE DATABASE keycloak;
        GRANT ALL PRIVILEGES ON DATABASE keycloak TO postgres;
  updateStrategy:
    type: RollingUpdate
    rollingUpdate: {}
  service:
    type: ClusterIP
    ports:
      postgresql: 5432
    loadBalancerIP: ""
    externalTrafficPolicy: Cluster
  persistence:
    enabled: true
    mountPath: /bitnami/postgresql
    storageClass: ""
    accessModes:
      - ReadWriteOnce
    size: 1Gi