apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: gitea
helmCharts:
- name: gitea
  includeCRDs: true
  version: 10.4.0
  repo: https://dl.gitea.io/charts/
  releaseName: appliance
  valuesFile: files/gitea.values.yaml
resources: 
- namespace.yaml











