apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: misp
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  syncPolicy:
    automated:
      prune: true
    syncOptions:
    - CreateNamespace=true
  source:
    path: argocd/apps/misp/kustomize/overlays/appliance
    repoURL: https://onprem.phl-imcite.net/gitea/fortress-manifests/crucible-appliance.git
    targetRevision: main
