apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd
patches:
  - patch: |-
      - op: remove
        path: /spec/template/spec/containers/0/env/0
    target:
      version: v1
      kind: StatefulSet
      labelSelector: "app.kubernetes.io/name=argocd-application-controller"

 




