apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: sei-smtp-relay
  namespace: monitoring
spec:
  route:
    groupBy: ['job']
    groupWait: 30s
    groupInterval: 5m
    repeatInterval: 12h
    receiver: 'sei-smtp-relay'
  receivers:
    - name: 'sei-smtp-relay'
      emailConfigs:
        - to: awilkey@sei.cmu.edu
          from: fortress-noreply@sei.cmu.edu
          smarthost: smtp.sei.cmu.edu:25
          hello: smtp.sei.cmu.edu
          requireTls: false
