---
- hosts: all
  become: yes
  vars:
  tasks:
    # - name: Update all packages
    #   apt:
    #     update_cache: yes
    #     upgrade: no
    #   when: ansible_os_family == "Debian"

    - name: Install required dependencies
      apt:
        name:
          - curl
          - apt-transport-https
          - ca-certificates
          - nfs-common
          - jq
          - unzip
          - tar
          - zstd
          
        state: present
      when: ansible_os_family == "Debian"
    
    - name: Grab yq latest binaries 
      unarchive: 
        src: "https://github.com/mikefarah/yq/releases/download/v4.45.1/yq_linux_amd64.tar.gz"
        dest: /usr/local/bin
        remote_src: true 
    
    - name: rename file
      command: mv /usr/local/bin/yq_linux_amd64 /usr/local/bin/yq
      become: yes

    - name: Ensure the yq binary is executable
      command: chmod +x /usr/local/bin/yq
    


    - name: Disable swap
      command: swapoff -a
      become: yes

    - name: Ensure swap is disabled in fstab
      replace:
        path: /etc/fstab
        regexp: '^\s*([^#\s]+\s+[^#\s]+\s+swap\s+[^#\s]+.*)$'
        replace: '# \1'
      become: yes

    - name: Open required ports for k3s
      ufw:
        rule: allow
        port: "{{ item }}"
        proto: tcp
      with_items:
        - 6443  # Kubernetes API server
        - 2379  # etcd server client API
        - 2380  # etcd server peer API
        - 10250 # Kubelet API
        - 10251 # kube-scheduler
        - 10252 # kube-controller-manager
      when: ansible_os_family == "Debian"

- hosts: "{{ groups['ctrl'][0] }}"
  tasks:
    - name: Install k3s on the first controller node
      shell: |
        curl -sfL https://get.k3s.io | INSTALL_K3S_VERSION="v1.31.3+k3s1" \
        K3S_KUBECONFIG_MODE="644" \
        K3S_TOKEN="crucible" \
        INSTALL_K3S_EXEC="server --disable traefik --embedded-registry --etcd-expose-metrics --prefer-bundled-bin --node-name {{ inventory_hostname }} --tls-san {{ domain }} --cluster-init" \
        sh -
      args:
        executable: /bin/bash
      become: yes

    - name: Get the k3s token
      command: cat /var/lib/rancher/k3s/server/node-token
      register: k3s_token
      changed_when: false
      become: yes

    - name: Display the IP address of the controller node
      debug: var=ansible_default_ipv4.address
    
    - name: Create a directory if it does not exist
      ansible.builtin.file:
        path: /home/{{ansible_user_id}}/.kube
        state: directory
        mode: '0744'

    - name: rename KUBECONFIG defaults
      ansible.builtin.replace:
        path: /etc/rancher/k3s/k3s.yaml
        regexp: 'default'
        replace: 'krates-crucible-appliance'
      become: yes

    - name: use yq to rename cluster, cluster user, and context
      ansible.builtin.command:
        cmd: yq -i '.clusters[0].cluster.server = "https://{{ansible_default_ipv4.address}}:6443" ' /etc/rancher/k3s/k3s.yaml
      become: yes

    - name: move kubectl config
      ansible.builtin.copy:
        src: /etc/rancher/k3s/k3s.yaml
        dest: /home/{{ansible_user_id}}/.kube/config
        remote_src: yes
        owner: "{{ansible_user_id}}"
        group: "{{ansible_user_id}}"
        mode: '0644'
      become: yes
      become_user: crucible
      changed_when: false
    
    - name: Copy kubeconfig to local machine
      fetch:
        src: /home/{{ansible_user_id}}/.kube/config
        dest: "{{ playbook_dir }}/kubeconfig_{{ inventory_hostname }}"
        flat: yes
      become: no

    - name: Merge kubeconfig with existing config
      shell: |
        KUBECONFIG={{ playbook_dir }}/kubeconfig_{{ inventory_hostname }}:~/.kube/config kubectl config view --flatten > ~/.kube/config_merged
        mv ~/.kube/config_merged ~/.kube/config
      args:
        executable: /bin/bash
      delegate_to: localhost
      
    
      

- hosts: "{{ groups['ctrl'][1:] }}"
  tasks:
    - name: Join other controller nodes to the cluster
      shell: |
        curl -sfL https://get.k3s.io | INSTALL_K3S_VERSION="v1.31.3+k3s1" \
        K3S_KUBECONFIG_MODE="644" \
        K3S_TOKEN="{{ hostvars[groups['ctrl'][0]].k3s_token.stdout }}" \
        INSTALL_K3S_EXEC="server --server https://{{ hostvars[groups['ctrl'][0]].ansible_default_ipv4.address }}:6443 --disable traefik --embedded-registry --etcd-expose-metrics --prefer-bundled-bin --node-name {{ inventory_hostname }}" \
        sh -
      args:
        executable: /bin/bash
      become: yes

- hosts: wrkr
  tasks:
    - name: Join worker nodes to the cluster
      shell: |
        curl -sfL https://get.k3s.io | INSTALL_K3S_VERSION="v1.31.3+k3s1" \
        K3S_KUBECONFIG_MODE="644" \
        K3S_TOKEN="{{ hostvars[groups['ctrl'][0]].k3s_token.stdout }}" \
        INSTALL_K3S_EXEC="agent --server https://{{ hostvars[groups['ctrl'][0]].ansible_default_ipv4.address }}:6443 --node-name {{ inventory_hostname }}" \
        sh -
      args:
        executable: /bin/bash
      become: yes
# - hosts: "{{ groups['ctrl'][0] }}"
#   become: yes
#   tasks:
#     - name: Install k3s Controller (First)
#       shell: |
#         curl -sfL https://get.k3s.io | INSTALL_K3S_VERSION="v1.31.3+k3s1" K3S_KUBECONFIG_MODE="644"  K3S_TOKEN="crucible" INSTALL_K3S_EXEC="server --disable traefik --embedded-registry --etcd-expose-metrics  --prefer-bundled-bin --node-name crucible-ctrl-01 --tls-san crucible.io --cluster-init" sh - 
        
#       args:
#         executable: /bin/bash
#       become: yes
#       when: groups['ctrl'][0]

#     - name: Get Controller Host Debug 
#       debug:
#         msg: "{{ groups['ctrl'][0] }}"  

#     - name: Install k3s Controller (Others)
#       shell: |
#         curl -sfL https://get.k3s.io | INSTALL_K3S_VERSION="v1.31.3+k3s1" K3S_KUBECONFIG_MODE="644"  K3S_TOKEN="crucible" INSTALL_K3S_EXEC="server --server {{ groups['ctrl'][0] }} --disable traefik --embedded-registry --etcd-expose-metrics  --prefer-bundled-bin --node-name crucible-ctrl-01 --tls-san crucible.io" sh - 
#       args:
#         executable: /bin/bash
#       become: yes
      


#     - name: Wait for k3s to be ready
#       command: kubectl get nodes
#       register: k3s_nodes
#       until: k3s_nodes.rc == 0
#       retries: 5
#       delay: 10

#     - name: Get the k3s token
#       command: cat /var/lib/rancher/k3s/server/node-token
#       register: k3s_token
