apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cert-manager
helmCharts:
- name: cert-manager
  includeCRDs: true
  version: 1.16.1
  repo: https://charts.jetstack.io
  releaseName: appliance
  valuesFile: files/cert-manager.values.yaml
  namespace: cert-manager
secretGenerator:
  - name: root-ca
    files: 
    - tls.crt=files/root-ca.pem
    - tls.key=files/root-ca.key
generatorOptions:
  disableNameSuffixHash: true
resources: 
- namespace.yaml











