apiVersion: v1
kind: PersistentVolume
metadata:
  name: player-pv
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: player-api
spec:
  resources:
    requests:
      storage: 10Gi
  accessModes:
    - ReadWriteMany
