apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: topomojo
configMapGenerator:
  - name: appliance-topomojo-api
    files:
    - start.sh=files/start.sh
    - root-ca.crt=files/root-ca.pem
generatorOptions:
  disableNameSuffixHash: true
helmCharts:
- name: topomojo
  includeCRDs: true
  version: 0.3.8
  repo: https://helm.cmusei.dev/charts
  releaseName: appliance
  valuesFile: files/topomojo.values.yaml
resources: 
- namespace.yaml
- topomojo-pvc.yaml











