apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: topomojo
secretGenerator:
generatorOptions:
  disableNameSuffixHash: true
helmCharts:
- name: topomojo
  includeCRDs: true
  version: 0.3.8
  repo: https://helm.cmusei.dev/charts
  releaseName: appliance
  valuesFile: files/topomojo.values.yaml
resources: 
- namespace.yaml
- topomojo-pvc.yaml











