apiVersion: v1
kind: PersistentVolume
metadata:
  name: topomojo-pv
spec:
  storageClassName: manual
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /volume1/VMWare/topomojo
    server: 192.168.1.253
    readOnly: false