apiVersion: v1
kind: PersistentVolume
metadata:
  name: topomojo-iso-pv
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: "/volume1/VMWare/topomojo/iso"
    server: "192.168.1.253"
    readOnly: false