apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: vault
helmCharts:
- name: nfs-server-provisioner
  includeCRDs: true
  version: 1.8.0
  repo: https://kvaps.github.io/charts
  releaseName: appliance
  valuesFile: files/nfs-server.values.yaml
resources: 
- namespace.yaml











