apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: <name>
  namespace: <namespace>
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: <dst_namespace>
    server: https://kubernetes.default.svc
  project: default
  syncPolicy:
    automated:
      prune: true
    syncOptions:
    - CreateNamespace=true
  sources:
  - path: <path>
    repoURL: file:///tmp/apps
    targetRevision: main
    directory:
      recurse: true

