apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-dns
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
  project: default
  syncPolicy:
    automated:
      prune: true
    syncOptions:
    - CreateNamespace=true
  source:
    path: argocd/install/external-dns/kustomize/overlays/appliance
    repoURL: https://crucible.io/gitea/fortress-manifests/crucible-appliance.git
    targetRevision: main

