alloy-api:
  image:
    repository: cmusei/alloy-api
    tag: 3.4.3
    pullPolicy: IfNotPresent
  command: ["bash", "-c", "update-ca-certificates && dotnet Alloy.Api.dll"]

  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: <path:fortress-prod/data/shared#ingress-class>
      nginx.ingress.kubernetes.io/proxy-read-timeout: "86400"
      nginx.ingress.kubernetes.io/proxy-send-timeout: "86400"
      nginx.ingress.kubernetes.io/use-regex: "true"
      cert-manager.io/cluster-issuer: ca-issuer
    hosts:
      - host: <path:fortress-prod/data/shared#domain>
        paths:
          - path: /alloy/(hubs|api|swagger)
            pathType: Prefix
    tls:
      - secretName: <path:fortress-prod/data/shared#domain>-tls
        hosts:
          - <path:fortress-prod/data/shared#domain>

  # If this deployment needs to trust non-public certificates,
  # create a configMap with the needed certifcates and specify
  # the configMap name here
  certificateMap: "root-ca"

  env:
    PathBase: "/alloy"
    CorsPolicy__Origins__0: https://<path:fortress-prod/data/shared#domain>
    CorsPolicy__AllowAnyMethod: true
    CorsPolicy__AllowAnyHeader: true
    Logging__LogLevel__Default: "<path:fortress-prod/data/shared#crucible-log-level>"
    Logging__LogLevel__System: "<path:fortress-prod/data/shared#crucible-log-level>"
    Logging__LogLevel__Microsoft: "<path:fortress-prod/data/shared#crucible-log-level>"
    Logging__Console__LogLevel__Default: "<path:fortress-prod/data/shared#crucible-log-level>"
    Logging__Console__LogLevel__System: "<path:fortress-prod/data/shared#crucible-log-level>"
    Logging__Console__LogLevel__Microsoft: "<path:fortress-prod/data/shared#crucible-log-level>"
    # Connection String to database
    ConnectionStrings__PostgreSQL: <path:fortress-prod/data/alloy#alloy-api-connection-string>

    # OAuth2 Identity Client for Application
    Authorization__Authority: https://<path:fortress-prod/data/shared#domain>/<path:fortress-prod/data/shared#oauth-provider>/<path:fortress-prod/data/shared#oauth-authority-url>
    Authorization__AuthorizationUrl: https://<path:fortress-prod/data/shared#domain>/<path:fortress-prod/data/shared#oauth-provider>/<path:fortress-prod/data/shared#oauth-authorization-url>
    Authorization__TokenUrl: https://<path:fortress-prod/data/shared#domain>/<path:fortress-prod/data/shared#oauth-provider>/<path:fortress-prod/data/shared#oauth-token-url>
    Authorization__AuthorizationScope: 'player-api alloy-api caster-api steamfitter-api vm-api'
    Authorization__ClientId: "<path:fortress-prod/data/shared#oauth-env>_<path:fortress-prod/data/shared#oauth-gid>_alloy-api"
    Authorization__ClientName: 'Alloy API'

    # OAuth2 Identity Client /w Password
    ResourceOwnerAuthorization__Authority: https://<path:fortress-prod/data/shared#domain>/<path:fortress-prod/data/shared#oauth-provider>/<path:fortress-prod/data/shared#oauth-authority-url>
    ResourceOwnerAuthorization__ClientId: "<path:fortress-prod/data/shared#oauth-env>_<path:fortress-prod/data/shared#oauth-gid>_alloy-admin"
    #ResourceOwnerAuthorization__ClientSecret: ""
    ResourceOwnerAuthorization__UserName: "<path:fortress-prod/data/shared#crucible-admin-user>" 
    ResourceOwnerAuthorization__Password: "<path:fortress-prod/data/shared#crucible-admin-pass>" 
    ResourceOwnerAuthorization__Scope: 'alloy-api player-api caster-api steamfitter-api vm-api'

    # Crucible Application URLs
    ClientSettings__urls__playerApi: https://<path:fortress-prod/data/shared#domain>/player/api
    ClientSettings__urls__casterApi: https://<path:fortress-prod/data/shared#domain>/caster/api
    ClientSettings__urls__steamfitterApi: https://<path:fortress-prod/data/shared#domain>/steamfitter/api

alloy-ui:
  image:
    repository: cmusei/alloy-ui
    pullPolicy: IfNotPresent
    tag: '3.2.6'

  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: <path:fortress-prod/data/shared#ingress-class>
      nginx.ingress.kubernetes.io/proxy-read-timeout: "86400"
      nginx.ingress.kubernetes.io/proxy-send-timeout: "86400"
      nginx.ingress.kubernetes.io/use-regex: "true"
      cert-manager.io/cluster-issuer: ca-issuer
    hosts:
      - host: <path:fortress-prod/data/shared#domain>
        paths:
          - path: "/alloy(/|$)(.*)"
            pathType: Prefix
    tls:
      - secretName: <path:fortress-prod/data/shared#domain>-tls
        hosts:
          - <path:fortress-prod/data/shared#domain>
  env:
    ## basehref is path to the app
    APP_BASEHREF: "/alloy"

  # Config app settings with a JSON file.
  # These values correspond to an OpenID connect client and
  # some basic configuration
  # NOTE:  PlayerUIAddress is the URL to the Crucible - Player application
  settings: |-
    {
      "ApiUrl": "https://<path:fortress-prod/data/shared#domain>/alloy",
      "OIDCSettings": {
        "authority": "https://<path:fortress-prod/data/shared#domain>/<path:fortress-prod/data/shared#oauth-provider>/<path:fortress-prod/data/shared#oauth-authority-url>",
        "client_id": "<path:fortress-prod/data/shared#oauth-env>_<path:fortress-prod/data/shared#oauth-gid>_alloy-ui",
        "redirect_uri": "https://<path:fortress-prod/data/shared#domain>/alloy/auth-callback",
        "post_logout_redirect_uri": "https://<path:fortress-prod/data/shared#domain>/alloy",
        "response_type": "code",
        "scope": "openid profile alloy-api player-api caster-api steamfitter-api vm-api",
        "automaticSilentRenew": true,
        "silent_redirect_uri": "https://<path:fortress-prod/data/shared#domain>/alloy/auth-callback-silent"
      },
      "AppTitle": "Alloy",
      "AppTopBarText": "Alloy",
      "AppTopBarHexColor": "#719F94",
      "AppTopBarHexTextColor": "#FFFFFF",
      "PlayerUIAddress": "https://<path:fortress-prod/data/shared#domain>/player",
      "PollingIntervalMS": "3500",
      "UseLocalAuthStorage": true
    }
