# hin blueprint sei/blueprint -f blueprint.values.yaml
blueprint-api:
  image:
    tag: "1.4.3"

# Ingress configuration example for NGINX
# TLS and Host URLs need configured
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: <path:fortress-prod/data/shared#ingress-class>
      nginx.ingress.kubernetes.io/proxy-read-timeout: '86400'
      nginx.ingress.kubernetes.io/proxy-send-timeout: '86400'
      nginx.ingress.kubernetes.io/use-regex: "true"
      cert-manager.io/cluster-issuer: ca-issuer
    hosts:
      - host: blueprint.<path:fortress-prod/data/shared#domain>
        paths:
          - path: /(api|swagger|hubs)
            pathType: Prefix
    tls:
      - secretName: blueprint.<path:fortress-prod/data/shared#domain>-tls
        hosts:
         - blueprint.<path:fortress-prod/data/shared#domain>

  resources:
    requests:
      cpu: 200m
      memory: 512Mi

  certificateMap: "root-ca"

  env:
    PathBase: ""
    # CORS policy settings.
    # The first entry should be the URL to Blueprint
    CorsPolicy__Origins__0: https://blueprint.<path:fortress-prod/data/shared#domain>

    CorsPolicy__AllowAnyHeader: true

    # Connection String to database
    # database requires the 'uuid-ossp' extension installed
    ConnectionStrings__PostgreSQL: <path:fortress-prod/data/blueprint#blueprint-db-connection-string>
    Database__SeedFile: seed-data.json
    Database__Provider: PostgreSQL
    Database__AutoMigrate: true
    Database__DevModeRecreate: false
    
    # OAuth2 Identity Client for Application
    Authorization__Authority: https://<path:fortress-prod/data/shared#domain>/keycloak/realms/crucible
    Authorization__AuthorizationUrl: https://<path:fortress-prod/data/shared#domain>/keycloak/realms/crucible/protocol/openid-connect/auth
    Authorization__TokenUrl: https://<path:fortress-prod/data/shared#domain>/keycloak/realms/crucible/protocol/openid-connect/token
    Authorization__AuthorizationScope: "blueprint-api cite-api gallery-api player-api vm-api steamfitter-api openid"
    Authorization__ClientId: "blueprint-api"
    Authorization__ClientName: "Blueprint API"

    ClientSettings__CiteApiUrl: "https://cite.<path:fortress-prod/data/shared#domain>"
    ClientSettings__GalleryApiUrl: "https://gallery.<path:fortress-prod/data/shared#domain>"
    ClientSettings__PlayerApiUrl: "https://player.<path:fortress-prod/data/shared#domain>"
    ClientSettings__SteamfitterApiUrl: "https://steamfitter.<path:fortress-prod/data/shared#domain>"

    ResourceOwnerAuthorization__Authority: https://<path:fortress-prod/data/shared#domain>/keycloak/realms/crucible
    ResourceOwnerAuthorization__ClientId: blueprint-admin
    ResourceOwnerAuthorization__UserName: "blueprint.admin"
    ResourceOwnerAuthorization__Password: <path:fortress-prod/data/shared#crucible-admin-pass>
    ResourceOwnerAuthorization__Scope: "openid profile blueprint-api cite-api gallery-api player-api email"

    Logging__Debug__LogLevel__System: "Information"
    Logging__Debug__LogLevel__Default: "Information"
    Logging__Debug__LogLevel__Microsoft: "Information"
    Logging__Console__LogLevel__System: "Information"
    Logging__Console__LogLevel__Microsoft: "Information"
    Logging__Console__LogLevel__Default: "Information"
    Logging__Console__FormatterName: "simple"
    Logging__Console__FormatterOptions__SingleLine: "true"
    Logging__Console__FormatterOptions__TimestampFormat: ""

blueprint-ui:
  # Docker image release version
  image:
    tag: "1.4.3"

  # Ingress configuration example for NGINX
  # TLS and Host URLs need configured
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: <path:fortress-prod/data/shared#ingress-class>
      cert-manager.io/cluster-issuer: ca-issuer
    hosts:
      - host: "blueprint.<path:fortress-prod/data/shared#domain>"
        paths:
          - path: /
            pathType: Prefix
    tls:
      - secretName: blueprint.<path:fortress-prod/data/shared#domain>-tls
        hosts:
         - "blueprint.<path:fortress-prod/data/shared#domain>"

  resources:
    requests:
      cpu: 200m
      memory: 10Mi

  env:
    APP_BASEHREF: ""
  # Config app settings with a JSON file.
  # These values correspond to an OpenID connect client and
  # some basic configuration
  settings: |-
    {
      "ApiUrl": "https://blueprint.<path:fortress-prod/data/shared#domain>",
      "GalleryApiUrl": "https://gallery.<path:fortress-prod/data/shared#domain>",
      "PlayerUrl": "https://player.<path:fortress-prod/data/shared#domain>",
      "OIDCSettings": {
        "authority": "https://<path:fortress-prod/data/shared#domain>/keycloak/realms/crucible",
        "client_id": "blueprint-ui",
        "redirect_uri": "https://blueprint.<path:fortress-prod/data/shared#domain>/auth-callback",
        "post_logout_redirect_uri": "https://blueprint.<path:fortress-prod/data/shared#domain>",
        "response_type": "code",
        "scope": "openid profile blueprint-api cite-api gallery-api player-api vm-api steamfitter-api",
        "automaticSilentRenew": true,
        "silent_redirect_uri": "https://blueprint.<path:fortress-prod/data/shared#domain>/auth-callback-silent"
      },
      "AppTitle": "Blueprint",
      "AppTopBarHexColor": "#2d69b4",
      "AppTopBarHexTextColor": "#FFFFFF",
      "AppTopBarText": "Blueprint  -  Collaborative MSEL Creation",
      "AppTopBarImage": "/assets/img/pencil-ruler-white.png",
      "UseLocalAuthStorage": false
    }
