# hin gallery sei/gallery -f gallery.values.yaml
gallery-api:
  image:
    tag: "1.6.0"
    pullPolicy: "IfNotPresent"

# Ingress configuration example for NGINX
# TLS and Host URLs need configured
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: <path:fortress-prod/data/shared#ingress-class>
      nginx.ingress.kubernetes.io/proxy-read-timeout: '86400'
      nginx.ingress.kubernetes.io/proxy-send-timeout: '86400'
      nginx.ingress.kubernetes.io/use-regex: "true"
      cert-manager.io/cluster-issuer: ca-issuer
    hosts:
      - host: <path:fortress-prod/data/shared#domain>
        paths:
          - path: /gallery/(api|swagger|hubs)
            pathType: Prefix
    tls:
      - secretName: <path:fortress-prod/data/shared#domain>-tls
        hosts:
         - <path:fortress-prod/data/shared#domain>

  resources:
    requests:
      cpu: 500m
      memory: 1024Mi

  env:
    PathBase: "/gallery"
    # CORS policy settings.
    # The first entry should be the URL to Gallery
    CorsPolicy__Origins__0: https://<path:fortress-prod/data/shared#domain>

    # Connection String to database
    # database requires the 'uuid-ossp' extension installed
    ConnectionStrings__PostgreSQL: <path:fortress-prod/data/gallery#gallery-db-connection-string> 

    # OAuth2 Identity Client for Application
    Authorization__Authority: https://<path:fortress-prod/data/shared#domain>/keycloak/realms/crucible
    Authorization__AuthorizationUrl: https://<path:fortress-prod/data/shared#domain>/keycloak/realms/crucible/protocol/openid-connect/auth
    Authorization__TokenUrl: https://<path:fortress-prod/data/shared#domain>/keycloak/realms/crucible/protocol/openid-connect/token
    Authorization__AuthorizationScope: "gallery-api"
    Authorization__ClientId: "<path:fortress-prod/data/shared#oauth-env>_<path:fortress-prod/data/shared#oauth-gid>_gallery-api"
    Authorization__ClientName: Gallery API

    # OAuth2 Identity Client /w Password
    ResourceOwnerAuthorization__Authority: https://<path:fortress-prod/data/shared#domain>/keycloak/realms/crucible
    ResourceOwnerAuthorization__ClientId: <path:fortress-prod/data/shared#oauth-env>_<path:fortress-prod/data/shared#oauth-gid>_gallery-admin"
    ResourceOwnerAuthorization__UserName: <path:fortress-prod/data/shared#crucible-admin-user>
    ResourceOwnerAuthorization__Password: <path:fortress-prod/data/shared#crucible-admin-pass>
    ResourceOwnerAuthorization__Scope: "steamfitter-api player-api vm-api"

    ClientSettings__SteamfitterApiUrl: https://<path:fortress-prod/data/shared#domain>/steamfitter/api
    ClientSettings__IsEmailActive: "true"

    Logging__Debug__LogLevel__System: "Warning"
    Logging__Debug__LogLevel__Default: "Warning"
    Logging__Debug__LogLevel__Microsoft: "Warning"
    Logging__Debug__FormatterName: "json"
    Logging__Debug__FormatterOptions__SingleLine: true
    Logging__Debug__FormatterOptions__TimestampFormat: "HH:mm:ss"
    Logging__Debug__FormatterOptions__UseUtcTimestamp: true
    Logging__Console__LogLevel__System: "Warning"
    Logging__Console__LogLevel__Default: "Warning"
    Logging__Console__LogLevel__Microsoft: "Warning"
    Logging__Console__FormatterName: "json"
    Logging__Console__FormatterOptions__SingleLine: true
    Logging__Console__FormatterOptions__TimestampFormat: "HH:mm:ss"
    Logging__Console__FormatterOptions__UseUtcTimestamp: true


gallery-ui:
  # Docker image release version
  image:
    tag: "1.6.3"
    pullPolicy: "IfNotPresent"

  # Ingress configuration example for NGINX
  # TLS and Host URLs need configured
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: <path:fortress-prod/data/shared#ingress-class>
      cert-manager.io/cluster-issuer: ca-issuer
    hosts:
      - host: <path:fortress-prod/data/shared#domain>
        paths:
          - path: /gallery
            pathType: Prefix
    tls:
      - secretName: appliance-cert
        hosts:
         - <path:fortress-prod/data/shared#domain>

  resources:
    requests:
      cpu: 200m
      memory: 10Mi

  env:
    APP_BASEHREF: "/gallery"
  # Config app settings with a JSON file.
  # These values correspond to an OpenID connect client and
  # some basic configuration
  settings: |-
    {
      "ApiUrl": "https://<path:fortress-prod/data/shared#domain>/gallery",
      "OIDCSettings": {
        "authority": "https://<path:fortress-prod/data/shared#domain>/keycloak/realms/crucible",
        "client_id": "<path:fortress-prod/data/shared#oauth-env>_<path:fortress-prod/data/shared#oauth-gid>_gallery-ui",
        "redirect_uri": "https://<path:fortress-prod/data/shared#domain>/gallery/auth-callback",
        "post_logout_redirect_uri": "https://<path:fortress-prod/data/shared#domain>/gallery",
        "response_type": "code",
        "scope": "openid profile gallery-api",
        "automaticSilentRenew": true,
        "silent_redirect_uri": "https://<path:fortress-prod/data/shared#domain>/gallery/auth-callback-silent"
      },
      "AppTitle": "Gallery",
      "AppTopBarHexColor": "#2d69b4",
      "AppTopBarHexTextColor": "#FFFFFF",
      "AppTopBarText": "Gallery  -  Keeping you in the know!",
      "AppTopBarImage": "/gallery/assets/img/monitor-dashboard-white.png",
      "UseLocalAuthStorage": false,
      "IsEmailActive": false,
      "useAccessTokenExpirtationRedirect": true
    }
