apiVersion: v1
kind: PersistentVolume
metadata:
  name: topomojo-pv-nfs
spec:
  storageClassName: longhorn-static
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /mnt/topomojo
    server: 10.2.196.4
  persistentVolumeReclaimPolicy: Retain
