apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: topomojo-pvc-nfs
  namespace: default
spec:
  storageClassName: nfs
  accessModes:
    - ReadWriteMany
  resources: 
    requests:
      storage: 24Gi
  volumeName: topomojo-pv-nfs
