apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base

patches:
  - target:
      kind: CronJob
      name: appliance-cron
    path: cronjob.yaml
  - target:
      kind: Deployment
      name: appliance-mkdocs-material
    path: deployment.yaml