apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: cert-manager
    server: https://kubernetes.default.svc
  project: default
  syncPolicy:
    automated:
      prune: true
    syncOptions:
    - CreateNamespace=true
  sources:
  - path: argocd/install/cert-manager/manifests
    repoURL: https://onprem.phl-imcite.net/gitea/fortress-manifests/crucible-appliance.git
    targetRevision: domain-change
    directory:
      recurse: true
  - path: argocd/install/cert-manager/kustomize/overlays/appliance
    repoURL: https://onprem.phl-imcite.net/gitea/fortress-manifests/crucible-appliance.git/
    targetRevision: domain-change

