apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd
resources: 
- cert-manager/Application.yaml
- nginx/Application.yaml
- http-echo/Application.yaml
- postgres/Application.yaml
- gitea/Application.yaml
- keycloak/Application.yaml
- topomojo/Application.yaml
