apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ingress-nginx
helmCharts:
- name: ingress-nginx
  includeCRDs: true
  version: v4.11.3
  repo: https://kubernetes.github.io/ingress-nginx
  releaseName: appliance
  valuesFile: files/ingress-nginx-4-11-3.values.yaml
  namespace: ingress-nginx
resources: 
- namespace.yaml









