apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: mkdocs
helmCharts:
  - name: mkdocs-material
    includeCRDs: true
    version: 0.1.0
    repo: https://helm.cmusei.dev/charts
    releaseName: appliance
    valuesFile: files/mkdocs-material.values.yaml













