---
- name: Prepare the node
  hosts: all
  gather_facts: yes
  tasks:
    - name: Install Packages
      ansible.builtin.package:
        name: 
          - make
          - curl 
          - software-properties-common 
          - apt-transport-https 
          - ca-certificates 
          - nfs-common
        state: present
      
    - name: Copy K3s binary
      ansible.builtin.copy:
        src: /home/crucible/crucible-appliance/dist/generic/k3s
        dest: /usr/local/bin
        owner: root
        group: root
        mode: '0755'
    
    - name: Create K3s Directory at /etc/rancher/k3s/
      ansible.builtin.file:
        path: /etc/rancher/k3s/
        state: directory
        owner: root
        group: root
        mode: '0755'      
    
    - name: Copy registries.yaml
      ansible.builtin.copy:
        content: |
          mirrors:
          docker.io:
            endpoint:
              - https://mirror.gcr.io
          "*":
        dest: /etc/rancher/k3s/registries.yaml
        owner: root
        group: root
        mode: '0600'
    
    - name: Copy node_token into memory
      ansible.builtin.slurp:
        src: /var/lib/rancher/k3s/server/node-token
      register: slurped_token
      delegate_to: localhost
      become: true

    - name: Write node_token from memory
      ansible.builtin.copy:
        backup: true
        dest: /home/crucible/node-token
        content: "{{ slurped_token['content'] | b64decode }}"
        owner: crucible
        group: crucible
        mode: '0777'
        
    - name: Increase inodes for asp.net applications
      ansible.builtin.lineinfile:
        line: fs.inotify.max_user_instances=524288
        path: /etc/sysctl.conf
        owner: root
        group: root
        mode: '0600'

    - name: Turn off swap
      ansible.builtin.command:
        cmd: swapoff -a 
        warn: no

    - name: Set Kernel Modules Persistently
      ansible.builtin.copy:
        content: |
          overlay
          br_netfilter
        dest: /etc/modules-load.d/k8s.conf
        owner: root
        group: root
        mode: '0600'
    
    - name: Load Kernel Modules
      ansible.builtin.command:
        cmd: modprobe overlay && modprobe br_netfilter

    - name: IPv6 Settings
      ansible.builtin.copy:
        content: |
          net.bridge.bridge-nf-call-ip6tables = 1
          net.bridge.bridge-nf-call-iptables = 1
          net.ipv4.ip_forward = 1
        dest: /etc/sysctl.d/k8s.conf
        owner: root
        group: root
        mode: '0600'
    
    - name: Apply sysctl settings
      ansible.builtin.command:
        cmd: sysctl --system

- name: Copy k3s-install.sh
  hosts: all
  gather_facts: yes
  tasks:
    - name: Copy k3s-install.sh 
      ansible.builtin.copy:
        src: /home/crucible/crucible-appliance/dist/generic/k3s-install.sh
        dest: /home/crucible/
        owner: crucible
        group: crucible
        mode: '0755'

- name: Install Agent / Worker nodes
  hosts: wrkr
  gather_facts: yes
  tasks:
    - name: Run K3s install script
      command:
        argv:
          - /home/crucible/k3s-install.sh
      environment:
        INSTALL_K3S_VERSION: "v1.31.3+k3s1"
        K3S_KUBECONFIG_MODE: "644"
        INSTALL_K3S_SKIP_DOWNLOAD: "true"
        INSTALL_K3S_EXEC: "agent --server https://crucible.io:6443 --prefer-bundled-bin --token-file /home/crucible/node-token"
      args:
        chdir: /home/crucible/

- name: Install Server / Controller nodes
  hosts: ctrl
  gather_facts: yes
  tasks:
    - name: Run K3s install script
      command:
        argv:
          - /home/crucible/k3s-install.sh
      environment:
        INSTALL_K3S_VERSION: "v1.31.3+k3s1"
        K3S_KUBECONFIG_MODE: "644"
        INSTALL_K3S_SKIP_DOWNLOAD: "true"
        INSTALL_K3S_EXEC: "server --server https://crucible.io:6443 --disable traefik --embedded-registry --etcd-expose-metrics --prefer-bundled-bin --tls-san crucible.io --prefer-bundled-bin --token-file /home/crucible/node-token"
      args:
        chdir: /home/crucible/
    
    # - name: Run K3s install script
    #   shell: >
    #     INSTALL_K3S_VERSION="v1.31.3+k3s1"
    #     K3S_KUBECONFIG_MODE="644"
    #     INSTALL_K3S_SKIP_DOWNLOAD=true
    #     INSTALL_K3S_EXEC="agent --server https://crucible.io:6443 --disable traefik --embedded-registry --etcd-expose-metrics --prefer-bundled-bin --tls-san crucible.io --token-file /home/crucible/node_token"
    #     /home/crucible/k3s-install.sh
    #   args:
    #     chdir: /home/crucible/