- name: Uninstall K3s
  hosts: wrkr
  gather_facts: yes
  tasks:
    - name: Run K3s uninstall script
      command: /usr/local/bin/k3s-agent-uninstall.sh

- name: Uninstall K3s
  hosts: ctrl
  gather_facts: yes
  tasks:
    - name: Run K3s uninstall script
      command: /usr/local/bin/k3s-uninstall.sh
        
    
    # - name: Run K3s install script
    #   shell: >
    #     INSTALL_K3S_VERSION="v1.31.3+k3s1"
    #     K3S_KUBECONFIG_MODE="644"
    #     INSTALL_K3S_SKIP_DOWNLOAD=true
    #     INSTALL_K3S_EXEC="agent --server https://crucible.io:6443 --disable traefik --embedded-registry --etcd-expose-metrics --prefer-bundled-bin --tls-san crucible.io --token-file /home/crucible/node_token"
    #     /home/crucible/k3s-install.sh
    #   args:
    #     chdir: /home/crucible/