apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mkdocs
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: mkdocs
    server: https://kubernetes.default.svc
  project: default
  syncPolicy:
    automated:
      prune: true
    syncOptions:
    - CreateNamespace=true
  sources:
  - path: argocd/prod-k8s/1-applications/mkdocs/kustomize/overlays/appliance
    repoURL: https://github.com/sei-noconnor/crucible-appliance.git
    targetRevision: main
    

