giteaServer: https://${DOMAIN}
owner: crucible

helm:
- name: sei
  repoUrl: https://helm.cmusei.dev/charts
  giteaUrl: https://${DOMAIN}/api/packages/${OWNER}/helm/api/charts
  items:
  - topomojo:0.3.8
  - player:1.4.5
  - alloy:1.4.1
  - steamfitter:1.4.2
  - caster:1.4.3 
  - blueprint:1.4.1
- name: bitnami
  repoUrl: https://dl.gitea.io/charts/
  giteaUrl: https://${DOMAIN}/api/packages/${OWNER}/helm/api/charts
  items:
  - keycloak:15.1.8
  - postgresql:12.8.0
- name: gitea
  repoUrl: https://charts.bitnami.com/bitnami
  giteaUrl: https://${DOMAIN}/api/packages/${OWNER}/helm/api/charts
  items:
  - gitea:1.4.0
- name: ingress-nginx
  repoUrl: https://kubernetes.github.io/ingress-nginx
  giteaUrl: https://${DOMAIN}/api/packages/${OWNER}/helm/api/charts
  items:
  - ingress-nginx:4.11.3
- name: argo-cd
  repoUrl: https://argoproj.github.io/argo-helm
  giteaUrl: https://${DOMAIN}/api/packages/${OWNER}/helm/api/charts
  items:
  - argocd:7.4.2

containers:
  giteaUrl: http://${DOMAIN}/api/v1/packages/${OWNER}/container/${ITEM}/${VERSION}
  items:
  
debian:
- distro: jammy
  os: ubuntu
  version: 22.04
  giteaUrl: http://${DOMAIN}/api/packages/${OWNER}/debian/pool/${DISTRO}/main/upload
  items:
  - build-essential avahi-daemon jq nfs-common sshpass postgresql-client make logrotate git vim
  - open-vm-tools

generic:
- giteaUrl: http://${DOMAIN}/api/packages/${OWNER}/generic/${FILE}/${FILE_VERSION}/${FILE_NAME}
  items:
  - https://releases.ubuntu.com/jammy/ubuntu-22.04.5-live-server-amd64.iso
  
git:
- giteaUrl: http://${DOMAIN}/api/
