apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: topomojo

helmCharts:
- name: topomojo
  includeCRDs: true
  version: 0.3.8
  repo: https://helm.cmusei.dev/charts
  releaseName: appliance
  valuesFile: files/topomojo.values.yaml
resources: 
- namespace.yaml
- console-ingress.yaml
- topomojo-pv.yaml
- topomojo-pvc.yaml

# replacements:
# - source:
#     version: v1
#     kind: PersistentVolume
#     name: topomojo-pv
#     fieldPath: spec.nfs.server
#   targets:
#   - select:
#       version: v1
#       name: topomojo-pv
#       kind: PersistentVolume
      











