apiVersion: v1
kind: PersistentVolume
metadata:
  name: topomojo-pv
spec:
  storageClassName: manual
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: ""
    server: ""
    readOnly: false