apiVersion: v1
kind: Secret
metadata:
  name: nfs-secret
  namespace: longhorn-system
type: Opaque
stringData:
  NFS_USERNAME: ~
  NFS_PASSWORD: ~
  
  # Parameters below are used for the compatible azure server for instance `Azurite` or 
  # you have a proxy to redirect the requests.
  #AZBLOB_ENDPOINT: ""
  #AZBLOB_CERT: ""
  #HTTP_PROXY: ""
  #HTTPS_PROXY: ""