apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: argocd-application-controller
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-application-controller
spec:
  template:
    spec:
      containers:
        - name: argocd-application-controller
          env:
            - name: REDIS_PASSWORD
              $patch: delete
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-repo-server
  namespace: argocd
spec:
  template:
    spec:
      containers:
        - name: argocd-repo-server
          env:
            - name: REDIS_PASSWORD
              $patch: delete
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-redis
  namespace: argocd
spec:
  template:
    spec:
      containers:
        - name: redis
          env:
            - name: REDIS_PASSWORD
              $patch: delete
          args:
            - '--save'
            - ''
            - '--appendonly'
            - 'no'
      initContainers:
        - name: secret-init
          $patch: delete