apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: cert-manager
    server: https://kubernetes.default.svc
  project: default
  syncPolicy:
    automated:
      prune: true
    syncOptions:
    - CreateNamespace=true
  sources:
  - path: cert-manager/manifests
    repoURL: file:///tmp/apps
    targetRevision: HEAD
    directory:
      recurse: true
  - path: cert-manager/kustomize/overlays/appliance
    repoURL: file:///tmp/apps
    targetRevision: HEAD
    kustomize:
      commonLabels:
        foo: bar