FROM debian:bookworm-slim

ARG RUNNER_VERSION="2.302.1"

ENV GITHUB_PERSONAL_TOKEN=""
ENV GITHUB_OWNER=""
ENV GITHUB_REPOSITORY=""
ENV CONTAINER_USER="github"


# Install Docker -> https://docs.docker.com/engine/install/debian/

# Add Docker's official GPG key:
RUN apt-get update && \
  apt-get install -y ca-certificates curl gnupg && \
  install -m 0755 -d /etc/apt/keyrings && \
  curl -fsSL https://download.docker.com/linux/debian/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg && \
  chmod a+r /etc/apt/keyrings/docker.gpg

# Add the repository to Apt sources:
RUN echo \
  "deb [arch="$(dpkg --print-architecture)" signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/debian \
  "$(. /etc/os-release && echo "$VERSION_CODENAME")" stable" | \
  tee /etc/apt/sources.list.d/docker.list > /dev/null
RUN apt-get update

# I only install the CLI, we will run docker in another container!
RUN apt-get install -y -q --allow-unauthenticated docker-ce-cli git sudo gcc

RUN useradd -m -s /bin/zsh github && \
    usermod -aG sudo github
    
RUN apt-get update && \
  apt-get install -y -q --allow-unauthenticated git sudo

RUN useradd -m -s /bin/zsh linuxbrew && \
  usermod -aG sudo linuxbrew &&  \
  mkdir -p /home/linuxbrew/.linuxbrew && \
  chown -R linuxbrew: /home/linuxbrew/.linuxbrew
USER linuxbrew
RUN /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
USER root
RUN chown -R github:github /home/linuxbrew/.linuxbrew
ENV PATH="/home/linuxbrew/.linuxbrew/bin:${PATH}"
RUN git config --global --add safe.directory /home/linuxbrew/.linuxbrew/Homebrew
USER github
RUN brew update
RUN brew doctor


USER github
WORKDIR /home/github
RUN curl -Ls https://github.com/actions/runner/releases/download/v${RUNNER_VERSION}/actions-runner-linux-x64-${RUNNER_VERSION}.tar.gz | tar xz \
  && sudo ./bin/installdependencies.sh

USER github
COPY --chown=github:github entrypoint.sh  /actions-runner/entrypoint.sh
RUN sudo chmod u+x /actions-runner/entrypoint.sh

#working folder for the runner 
USER github
RUN sudo mkdir /work 

ENTRYPOINT ["/actions-runner/entrypoint.sh"]