apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nfs-server
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: nfs-server
    server: https://kubernetes.default.svc
  project: default
  syncPolicy:
    automated:
      prune: true
    syncOptions:
    - CreateNamespace=true
  sources:
  - path: argocd/install/nfs-server/kustomize/overlays/appliance
    repoURL: https://onprem.phl-imcite.net/gitea/fortress-manifests/crucible-appliance.git
    targetRevision: domain-change

