name: build

on:
  push:
    branches:
      - github-runner
      - main
  pull_request:
  release:
    types: [published]

jobs:
  build:
    runs-on: self-hosted
    steps:
    - name: Display ENV
      run: env

    - name: Checkout Code
      uses: actions/checkout@v4
      with:
        repository: 'sei-noconnor/crucible-appliance'
        
    - name: Packer Version
      run: which packer && packer version

    - name: Write Appliance.yaml
      env:
          ENVIRONMENT_HOUSE: ${{ secrets.CRUCIBLE_ENVIRONMENT_HOUSE }}
      run: 'echo "$ENVIRONMENT" > appliance.yaml'
      
    