name: build

on:
  push:
    branches:
      - github-runner
      - main
  pull_request:
  release:
    types: [published]

jobs:
  build:
    runs-on: self-hosted
    environment: House
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
      with:
        repository: 'sei-noconnor/crucible-appliance'
        
    - name: Packer Version
      run: which packer && packer version

    - name: Write Appliance.yaml
      run: |
        APPLIANCE_YAML=$(cat << EOF
        vars:
          vsphere_server: "${{ vars.CRUCIBLE_VSPHERE_SERVER }}"
          vsphere_user: "${{ secrets.CRUCIBLE_VSPHERE_USER }}"
          vsphere_password: "${{ secrets.CRUCIBLE_VSPHERE_PASSWORD }}"
          vsphere_template: "${{ vars.CRUCIBLE_VSPHERE_TEMPLATE }}"
          datacenter: "${{ vars.CRUCIBLE_VSPHERE_DATACENTER }}"
          cluster: "${{ vars.CRUCIBLE_VSPHERE_CLUSTER }}"
          host: "${{ vars.CRUCIBLE_VSPHERE_HOST }}"
          datastore: "${{ vars.CRUCIBLE_VSPHERE_DATASTORE }}"
          network_name: "${{ vars.CRUCIBLE_VSPHERE_NETWORK }}"
          ssh_username: "${{ secrets.CRUCIBLE_OS_USER }}"
          ssh_password: "${{ secrets.CRUCIBLE_OS_PASSWORD }}"
        EOF
        )
        echo "$APPLIANCE_YAML" > appliance.yaml
      
    