name: build

on:
  push:
    branches:
      - github-runner
      - main
  pull_request:
  release:
    types: [published]

jobs:
  build:
    runs-on: self-hosted
    steps:
    - name: Display ENV
      run: env

    - name: Checkout Code
      uses: actions/checkout@v4
      with:
        repository: 'sei-noconnor/crucible-appliance'
        
    - name: Packer Version
      run: which packer && packer version

    - name: Write Appliance.yaml
      env:
          ENVIRONMENT_HOUSE: ${{ secrets.CRUCIBLE_ENVIRONMENT_HOUSE }}
      run: 'echo "$ENVIRONMENT_HOUSE" > appliance.yaml'

    - name: Build OVF image
      uses: nick-fields/retry@v2
      env:
        GITHUB_PULL_REQUEST: ${{ github.event.number }}
      with:
        timeout_minutes: 120
        max_attempts: 3
        command: make build
    - name: Get build_name from OVF file
      run: echo "build_name=$(sh -c "find . -name '*.ovf' | xargs basename -s '.ovf'")"
      working-directory: ./dist/output

    - name: Display build name
      run: echo ${{ env.build_name }}

    - name: Package OVA image
      run: tar -cvf $VM_NAME.ova --format=ustar $VM_NAME{.ovf,-disk001.vmdk,.mf}
      working-directory: ./dist/output

    - name: Upload OVA to Azure Storage
      run: |
        az cloud set --name AzureUSGovernment
        az storage blob upload --file $VM_NAME.ova \
                               --container-name crucible-appliance \
                               --name \"crucible-appliance-$VM_NAME.ova\"
                               --connection-string "${{ secrets.AZ_STORAGE_CS }}" \
                               --no-progress
    