name: packer-builder

on: [workflow_dispatch]

jobs:
  login:
    runs-on: crucible
    steps:
      - name: Login to onprem.imcite-phl.net registry
        uses: docker/login-action@v3
        with:
          registry: onprem.imcite-phl.net
          username: ${{ githu.actor }}
          password: crucible
      
      - name: Set up docker Buildx
        uses: docker/build-push-action@v6
      
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .github/runners
          push: true
          tags: fortress-manifests/packer:crucible

