
{{- if not .Values.mispPersistentVolumes.misp.existing }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "misp.fullname" . }}-pvc
  namespace: {{ .Values.mispPersistentVolumes.misp.namespace | default "default" }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.mispPersistentVolumes.misp.size }}
  storageClassName: {{ .Values.mispPersistentVolumes.misp.storageClassName }}
{{- end }}